name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew assembleDebug lintVitalRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk