name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build Release with Gradle
      run: ./gradlew clean assembleRelease --no-daemon
    - name: Sign app APK
      uses: kevin-david/zipalign-sign-android-release@v2
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.MATERIALFILES_KEYSTORE }}
        alias: ${{ secrets.MATERIALFILES_ALIAS }}
        keyStorePassword: ${{ secrets.MATERIALFILES_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.MATERIALFILES_KEYSTORE_PASSWORD_ALIAS }}
        zipAlign: true
      env:
        BUILD_TOOLS_VERSION: "36.0.0"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaterialFiles
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
